### ISSUE TITLE
Design response submission workflow

### ISSUE THREAD

**Issue by wbadart** [wbadart/coolsnappy#10]
**User Story:**
As a developer, I want a clear vision of the steps a user will take when responding to a survey, so that I will have strong guidance for my implementation.

**Description:**
The wiki article [_Conceptual Lifecycle of a Survey_](https://help.github.com/en/github/authenticating-to-github/signing-commits) along with #4 lay the groundwork for this workflow. Now we need to envision the detailed subprocesses that make up survey responses.

**Acceptance Criteria:**
- [ ] Documentation (a write-up and/ or a diagram) of the flow
  - Identify the domain events that can trigger this workflow
  - Identify the input data needed
  - Identify the outputs
  - Identify decision points and feedback loops

**Comment by alexandratsitsiringos** [comment]
This post is in the process of being re-edited and changed/adjusted.

**Domain Model (Stage 3)**

_Question Aggregate_
- Question (Aggregate Root)
- QuestionType (Child Entity)
- DraftSurvey (Value Object)
- PublishedSurvey (Value Object)
- SharingOption (Child Entity) 

_Answer Aggregate_
- Answer/Responder (Aggregate Root)
- AnswerType (Child Entity)
- ReportType (Child Entity)
- CompletedSurvey (Value Object)
- ResponsesCollected (Value Object)

_Domain Events_
- CreateSurvey
- PublishSurvey
- CollectResponses

**Input Types**
- set of answered questions, format determined by creator 
- report choice by creator 
Beyond MVP Input Types: 
- creator wants to edit questions and answer formats, after publication 
- responder wants to edit answers, after first submission

**Output Types**
- Draft Version of Questions Created
_view questions as your responder would view them_
- Summary Report
_list of responses for short answer type question, pie chart or bar chart for multiple choice_
- Excel/CSV Compilation of Data

**Beyond MVP Output**
- Individual Report
_list responses based on individual_
- Question-Based Report
_list responses based on question_
- Official Report
_professionally-looking PDF file with all the answers collected based on the creator's choice of presentation responses_ 

**Decision Points**
- Survey Report Type Chosen 
- Allow multiple submissions or allow responder to edit answers (Allow the creator to remove certain survey responses and view the data without them, either for data analysis purposes or to ensure the second set of answers is included instead of the first. Alternatively we could overwrite first set of answers) 

**Feedback Loops**
Input might need to be re-used to produce new output in the following cases/triggered by the following domain events:
- SurveyReOpened 
- ReportTypeChanged
 Beyond MVP: 
- ResponderRequestsEdits (after responding once)
- CreatorRequestsEdits (after publication)

**Comment by wbadart** [comment]
When we get on the phone next, let's try to refine this from the perspective of the survey taker. For example, I don't think "CreateSurvey" would be an event in this domain; if I'm to the point of submitting a response, then CreateSurvey must have already been handled.

**Comment by wbadart** [comment]
Response workflow:
- Survey responder has an interface for constructing an unvalidated response
- On response submission: validate according required questions and other such survey metadata
  - Unconditionally report validation result to responder
  - On success: emit response DTO (e.g. to reporting/ analytics domain)

**Comment by alexandratsitsiringos** [comment]
Report workflow: 

Report and analytics are derived from the same system (and perhaps even DTO)
