### ISSUE TITLE
DDD Homework

### ISSUE THREAD

**Issue by wbadart** [wbadart/coolsnappy#5]
This issue is for getting @alexandratsitsiringos ramped up on some DDD material to make sure we're on the same page during future discussions on the subject. Basically everything I recommend is going to be something that came out of Scott Wlaschin's mouth.

To start, here's the conference talk version of the book that will shortly be on its way to you:
- [x] https://www.youtube.com/watch?v=PLFl95c-IiU

This other talk of his is a good follow up (I'll say it's optional material though since it isn't strictly about DDD):
- [x] https://www.youtube.com/watch?v=srQt1NAHYC0

I'd then read through the materials I linked in #2:
- [x] https://fsharpforfunandprofit.com/series/designing-with-types.html
- [x] https://github.com/wbadart/haskell-dmmf (Mainly `src/Data/Domain/OrderTaking.lhs`)
- [x] https://github.com/swlaschin/DomainModelingMadeFunctional (Start with `src/OrderTaking/PlaceOrder.PublicTypes.fs` and click around from there)

Finally, go though this talk for a take on the intro DDD material other than Scott's:
- [x] https://www.youtube.com/watch?v=U6CeaA-Phqo

(You can use the check-marks as you go just to give me a sense of what you've covered so far.)

**Comment by alexandratsitsiringos** [comment]
Closes #5
The key takeaways from the videos and research I did on DDD were two main points:
- The code functions as its own documentation — comments are obsolete because the context and purpose of each function and entity is evident from the code itself 
- DDD allows for flexibility and ease of communication between different employees and contributors, as well as clients and developers. Someone from a more business oriented background would be able to delve into the code and understand what it does more easily compared to other programming paradigms. The same applies to a client, who could provide feedback much easier. 

Overview of DDD: 
Using DDD code naturally builds up a set of classes and interfaces that reflect the domain concepts. This is how you achieve harmonious models, by using the same terminology in conversations, models, and code. The result is a task-oriented user interface that matches the mental model of the user, or an API that makes sense to new developers familiar with the domain.
Certain concepts in the domain discussion are key. They will have activities centered on them and may define some common terms differently than other areas. In other words, islands will begin to form in the models and conversations around bounded contexts, which are subsets of the code that have their own, independent model, with a specific interface for use by other parts of the code.
The typical pattern for a context boundary is a set of commands accepted externally, with data/object transformations at the boundary from “outside” to “inside.” All external knowledge and dependencies are kept at bay by this boundary, allowing the code inside the boundary to use only its own subdomain-specific classes, interfaces, and terms. This supports independent development streams, with communication via well-defined interfaces.
This also supports one more activity: context mapping. This consists of identifying and classifying the relationships between bounded contexts within the domain.

Key Terms:
* Context
* Model
* Ubiquitous Language
* Bounded Context
* Entity
* Value Object
* Aggregate 
* Domain Event
* Service
* Repositories
* Factories 


DDD Advantages:
- Eases Communication
- Improves Flexibility 
- Emphasizes Domain over Interface
DDD Disadvantages:
- Encourages Iterative Practices
- Ill-Suited for Highly Technical Projects
- Requires Robust Domain Expertise

Sources: 
https://dzone.com/articles/an-introduction-to-domain-driven-design-and-its-be
https://www.pushingthestack.com/books/ddd/
https://techbeacon.com/app-dev-testing/get-your-feet-wet-domain-driven-design-3-guiding-principles
https://airbrake.io/blog/software-design/domain-driven-design  
https://martinfowler.com/bliki/BoundedContext.html

**Comment by wbadart** [comment]
Couldn't have put it better myself!
